# **Classification Problem**

In [ ]:
# Step 1: Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.svm import SVC
from sklearn.preprocessing import (
    StandardScaler,
    LabelEncoder,
    OneHotEncoder,
    OrdinalEncoder
)
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
# Download dataset: https://drive.google.com/file/d/1T4oy9neutVe2egrEcnjhKwAdHJCyDcJ6/view
!gdown 1T4oy9neutVe2egrEcnjhKwAdHJCyDcJ6

Downloading...
From: https://drive.google.com/uc?id=1T4oy9neutVe2egrEcnjhKwAdHJCyDcJ6
To: /content/breast-cancer.csv
100% 24.4k/24.4k [00:00<00:00, 73.7MB/s]

In [ ]:
# Step 2: read dataset
dataset_path = "/content/breast-cancer.csv"
df = pd.read_csv(
    dataset_path,
    names=[
        'age',
        'meonpause',
        'tumor-size',
        'inv-nodes',
        'node-caps',
        'deg-malig',
        'breast',
        'breast-quad',
        'irradiat',
        'label',
    ]
)
df

         age  meonpause tumor-size  ... breast-quad irradiat                   label
0    '40-49'  'premeno'    '15-19'  ...   'left_up'     'no'     'recurrence-events'
1    '50-59'     'ge40'    '15-19'  ...   'central'     'no'  'no-recurrence-events'
2    '50-59'     'ge40'    '35-39'  ...  'left_low'     'no'     'recurrence-events'
3    '40-49'  'premeno'    '35-39'  ...  'left_low'    'yes'  'no-recurrence-events'
4    '40-49'  'premeno'    '30-34'  ...  'right_up'     'no'     'recurrence-events'
..       ...        ...        ...  ...         ...      ...                     ...
281  '50-59'     'ge40'    '30-34'  ...  'left_low'     'no'  'no-recurrence-events'
282  '50-59'  'premeno'    '25-29'  ...  'left_low'    'yes'  'no-recurrence-events'
283  '30-39'  'premeno'    '30-34'  ...  'right_up'     'no'  'no-recurrence-events'
284  '50-59'  'premeno'    '15-19'  ...  'left_low'     'no'  'no-recurrence-events'
285  '50-59'     'ge40'    '40-44'  ...  'right_up'     'no'  'no-recurrence-events'

[286 rows x 10 columns]

In [ ]:
# Step 3: Dataset  Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          286 non-null    object
 1   meonpause    286 non-null    object
 2   tumor-size   286 non-null    object
 3   inv-nodes    286 non-null    object
 4   node-caps    278 non-null    object
 5   deg-malig    286 non-null    object
 6   breast       286 non-null    object
 7   breast-quad  285 non-null    object
 8   irradiat     286 non-null    object
 9   label        286 non-null    object
dtypes: object(10)
memory usage: 22.5+ KB

In [ ]:
df.describe()

            age  meonpause  ... irradiat                   label
count       286        286  ...      286                     286
unique        6          3  ...        2                       2
top     '50-59'  'premeno'  ...     'no'  'no-recurrence-events'
freq         96        150  ...      218                     201

[4 rows x 10 columns]

In [ ]:
# Return the mode(s) of the Series.
# The mode is the value that appears most often. There can be multiple modes.
# Always returns Series even if only one value is returned.
df['node-caps'].mode()

0    'no'
Name: node-caps, dtype: object

In [ ]:
# Step 4: Filling missing values
# Fill with the most appears value
df['node-caps'] = df['node-caps'].fillna(
    df['node-caps'].mode()[0]
)
df['breast-quad'] = df['breast-quad'].fillna(
    df['breast-quad'].mode()[0]
)

In [ ]:
df.describe()

            age  meonpause  ... irradiat                   label
count       286        286  ...      286                     286
unique        6          3  ...        2                       2
top     '50-59'  'premeno'  ...     'no'  'no-recurrence-events'
freq         96        150  ...      218                     201

[4 rows x 10 columns]

In [ ]:
# Step 5: Encode categorical features
for col_name in df.columns:
    n_uniques = df[col_name].unique()
    print(f"Unique values in {col_name}: {n_uniques}")

Unique values in age: ["'40-49'" "'50-59'" "'60-69'" "'30-39'" "'70-79'" "'20-29'"]
Unique values in meonpause: ["'premeno'" "'ge40'" "'lt40'"]
Unique values in tumor-size: ["'15-19'" "'35-39'" "'30-34'" "'25-29'" "'40-44'" "'10-14'" "'0-4'"
 "'20-24'" "'45-49'" "'50-54'" "'5-9'"]
Unique values in inv-nodes: ["'0-2'" "'3-5'" "'15-17'" "'6-8'" "'9-11'" "'24-26'" "'12-14'"]
Unique values in node-caps: ["'yes'" "'no'"]
Unique values in deg-malig: ["'3'" "'1'" "'2'"]
Unique values in breast: ["'right'" "'left'"]
Unique values in breast-quad: ["'left_up'" "'central'" "'left_low'" "'right_up'" "'right_low'"]
Unique values in irradiat: ["'no'" "'yes'"]
Unique values in label: ["'recurrence-events'" "'no-recurrence-events'"]

In [ ]:
# Non-ranking features: meonpause, node-caps, breast, breast-quad, irradiat
# ranking features: age, tumor-size, inv-nodes, deg-malig

# For non-ranking features: Apply One-hot encoding
# For ranking features: Apply Ordinal Encoding
non_rank_features = [
    'meonpause',
    'node-caps',
    'breast',
    'breast-quad',
    'irradiat'
]
rank_features = [
    'age',
    'tumor-size',
    'inv-nodes',
    'deg-malig'
]

y = df['label']
X = df.drop('label', axis=1)

In [ ]:
transformer = ColumnTransformer(
    transformers=[
        ("OneHot", OneHotEncoder(drop='first'), non_rank_features),
        ("Ordinal", OrdinalEncoder(), rank_features)
    ],
    remainder='passthrough'
)
X_transformed = transformer.fit_transform(X)

In [ ]:
onehot_features = transformer.named_transformers_['OneHot'].get_feature_names_out(non_rank_features)
all_features = onehot_features.tolist() + rank_features
X_encoded = pd.DataFrame(
    X_transformed,
    columns=all_features
)

In [ ]:
X_encoded

     meonpause_'lt40'  meonpause_'premeno'  ...  inv-nodes  deg-malig
0                 0.0                  1.0  ...        0.0        2.0
1                 0.0                  0.0  ...        0.0        0.0
2                 0.0                  0.0  ...        0.0        1.0
3                 0.0                  1.0  ...        0.0        2.0
4                 0.0                  1.0  ...        4.0        1.0
..                ...                  ...  ...        ...        ...
281               0.0                  0.0  ...        5.0        1.0
282               0.0                  1.0  ...        4.0        1.0
283               0.0                  1.0  ...        5.0        1.0
284               0.0                  1.0  ...        0.0        1.0
285               0.0                  0.0  ...        0.0        2.0

[286 rows x 13 columns]

In [ ]:
# Step 6: Encode Label
# Apply Label Encoder
labelEncoder = LabelEncoder()
y_encoded = labelEncoder.fit_transform(y)

In [ ]:
y_encoded

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Step 7: Normalization
normalizer = StandardScaler()
X_normalized = normalizer.fit_transform(X_encoded)

In [ ]:
# Step 8: Split train, val, test set
# 7:2:1
val_size = 0.2
test_size = 0.125
random_state = 0
is_shuffle = True

X_train, X_val, y_train, y_val = train_test_split(
    X_normalized, y_encoded,
    test_size=val_size,
    shuffle=is_shuffle,
    random_state=random_state
)
X_train, X_test, y_train, y_test = train_test_split(
    X_train, y_train,
    test_size=test_size,
    shuffle=is_shuffle,
    random_state=random_state
)

In [ ]:
print(f"Number of training samples: {X_train.shape[0]}")
print(f"Number of val samples: {X_val.shape[0]}")
print(f"Number of test samples: {X_test.shape[0]}")

Number of training samples: 199
Number of val samples: 58
Number of test samples: 29

In [ ]:
# Step 9: Train and evaluate SVM model
classifier = SVC(
    random_state=random_state
)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
y_val_pred = classifier.predict(X_val)
y_test_pred = classifier.predict(X_test)
val_scores = accuracy_score(y_val_pred, y_val)
test_scores = accuracy_score(y_test_pred, y_test)

print("Evaluation results on validation and test set:")
print(f"Val accuracy: {val_scores}")
print(f"Test accuracy: {test_scores}")

Evaluation results on validation and test set:
Val accuracy: 0.7241379310344828
Test accuracy: 0.7586206896551724